"""empty message

Revision ID: 3060d9b852ab
Revises: 8661e83b76e9
Create Date: 2022-01-27 14:31:54.605857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3060d9b852ab'
down_revision = '8661e83b76e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_portfolio', sa.Column('weight', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_portfolio', 'weight')
    # ### end Alembic commands ###
