"""empty message

Revision ID: f8584b069665
Revises: d75a465afa69
Create Date: 2022-01-27 12:58:03.890465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8584b069665'
down_revision = 'd75a465afa69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_history', sa.Column('date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price_history', 'date')
    # ### end Alembic commands ###
